name: Wektoryzacja ZIP do Qdrant

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          

      - name: Install dependencies
        run: |
          pip install qdrant-client sentence-transformers fastembed lxml tqdm
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run embedding script
        env:
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        run: python embed_github.py
